# Generated by Django 2.2.3 on 2019-07-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('deliveryTime', models.CharField(choices=[('1', '10AM-to-1PM'), ('2', '1PM-to-4PM'), ('3', '4PM-to-7PM'), ('4', '7PM-to-10PM')], max_length=1)),
                ('payment_options', models.CharField(choices=[('1', 'Card'), ('2', 'Cash on Delivery')], default='1', max_length=1)),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_app.Profile')),
            ],
        ),
    ]
