# Generated by Django 2.2.3 on 2019-07-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0003_auto_20190725_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='popsicle',
            name='category',
            field=models.CharField(choices=[('O', 'Organic'), ('N', 'Natural'), ('F', 'Fresh'), ('V', 'Vegetable'), ('GF', 'Gluten Free'), ('EB', 'Events Box')], default='O', max_length=2),
            preserve_default=False,
        ),
    ]
