# Generated by Django 2.2.3 on 2019-07-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0004_popsicle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='popsicle',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
