# Generated by Django 2.2.3 on 2019-07-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0005_popsicle_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popsicle',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popsicle',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
