# Generated by Django 2.2.3 on 2019-07-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0006_auto_20190726_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popsicle',
            name='popsicle_type',
        ),
    ]
