# Generated by Django 2.2.3 on 2019-07-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0007_remove_popsicle_popsicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popsicle',
            old_name='quantity',
            new_name='totalـquantity',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
