# Generated by Django 2.2.3 on 2019-07-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0008_auto_20190726_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.ImageField(default='1', upload_to=''),
        ),
    ]
