# Generated by Django 2.2.3 on 2019-07-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0010_auto_20190726_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='purchaser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='final_app.Profile'),
            preserve_default=False,
        ),
    ]
