# Generated by Django 2.2.3 on 2019-07-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0011_orderproduct_purchaser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='purchaser',
            new_name='user',
        ),
    ]
