# Generated by Django 2.2.3 on 2019-07-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0012_auto_20190726_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='purchaser',
            new_name='user',
        ),
    ]
