# Generated by Django 2.2.3 on 2019-07-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0015_auto_20190726_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='popsicle',
            name='totalـquantity',
            field=models.IntegerField(default=1),
        ),
    ]
