# Generated by Django 2.2.3 on 2019-07-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0016_auto_20190728_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.IntegerField(default=1),
        ),
    ]
