# Generated by Django 2.2.3 on 2019-07-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0017_auto_20190728_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='popsicleId',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
