# Generated by Django 2.2.3 on 2019-07-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0019_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryTime',
            new_name='delivery_Time',
        ),
    ]
