# Generated by Django 2.2.3 on 2019-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popsicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('UPC', models.CharField(max_length=12)),
                ('flavor', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('popsicle_type', models.CharField(choices=[('I', 'IceCream'), ('F', 'Freezie')], max_length=1)),
                ('production_date', models.DateField(auto_now=True)),
                ('expiration_date', models.DateField(auto_now=True)),
                ('quantity', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
